---

pdns_lib_dir: /usr/lib/powerdns

pdns_packages:
  - powerdns
  - python-requests
  - python-urllib3
  - python-netaddr

_pdns_backend_packages:
  mysql:
    - mariadb-libs
    - python-mysqlclient

pdns_owner: powerdns
pdns_group: powerdns
