---

pdns_packages:
  - pdns-server

pdns_dependencies:
  - gnupg

# The directory where the PowerDNS Authoritative Server configuration is located
pdns_config_dir: "/etc/powerdns"

pdns_owner: pdns
pdns_group: pdns

# # The name of the PowerDNS Authoritative Server package
# default_pdns_package_name: "pdns-server"
#
# # The name of the PowerDNS Authoritative Server debug package
# default_pdns_debug_symbols_package_name: "pdns-server-dbg"

# Packages needed to install MySQL
# pdns_mysql_packages:
#   - default-mysql-client
#   - python-mysqldb
#   - python3-mysqldb

# List of PowerDNS Authoritative Server Backends packages on Debian
_pdns_backend_packages:
  geo: pdns-backend-geo
  geoip: pdns-backend-geoip
  mysql:
    - pdns-backend-mysql
    - python3-mysqldb
  pgsql: pdns-backend-pgsql
  sqlite3: pdns-backend-sqlite3
  ldap: pdns-backend-ldap
  lmdb: pdns-backend-lmdb
  lua: pdns-backend-lua
  mydns: pdns-backend-mydns
  pipe: pdns-backend-pipe
  remote: pdns-backend-remote
  tinydns: pdns-backend-tinydns
