---

namespace: bodsch
name: dns

version: 1.0.0

readme: README.md

authors:
  - Bodo Schulz <bodo@boone-schulz.de>

description: A collection of Ansible roles for DNS handling.

license:
  - Apache-2.0

license_file: ''

tags:
  - infrastructure
  - linux
  - tools
  - system
  - dns

dependencies:
  community.general: ">=10.3.0"
  ansible.utils: "*"
  bodsch.core: ">=2.6.3"

repository: https://github.com/bodsch/ansible-collection-dns
documentation: https://github.com/bodsch/ansible-collection-dns/README.md
homepage: https://github.com/bodsch/ansible-collection-dns
issues: https://github.com/bodsch/ansible-collection-dns/issues

build_ignore:
  - "galaxy.yml"
  - "*.pyc"
  - "*.retry"
  - ".ansible-lint"
  - ".editorconfig"
  - ".flake8"
  - ".gitignore"
  - ".yamllint"
  - ".github"
