---

- name: do facts module to get latest information
  ansible.builtin.setup:
    # gather_subset:
    #   - 'network'
    #   - 'all_ipv4_addresses'
    #   - 'all_ipv6_addresses'

- name: merge bind configuration between defaults and custom
  ansible.builtin.set_fact:
    bind_listen: "{{ bind_defaults_listen | combine(bind_listen, recursive=True) }}"
    bind_statistics: "{{ bind_defaults_statistics | combine(bind_statistics, recursive=True) }}"
    bind_logging: "{{ bind_defaults_logging | combine(bind_logging, recursive=True) }}"
    bind_zone_soa: "{{ bind_defaults_zone_soa | combine(bind_zone_soa, recursive=True) }}"

- name: create runtime directories
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0770
  loop:
    - "{{ bind_dir }}/dynamic"
    - "{{ bind_dir }}/data"
    - "{{ bind_zone_dir }}"
  tags:
    - bind

- name: create directory for cached secondary zones
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ bind_secondary_dir }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0770
  tags:
    - bind

- name: create extra config for authenticated XFR request
  become: true
  ansible.builtin.template:
    src: etc/auth_transfer.j2
    dest: "{{ bind_conf_dir }}/{{ auth_file }}"
    owner: root
    group: "{{ bind_group }}"
    mode: 0640
  when:
    - bind_dns_keys is defined
    - bind_dns_keys | length > 0
  notify:
    - reload bind
  tags:
    - bind

- name: configure
  ansible.builtin.include_tasks: configure/zones.yml

- name: create main bind config file {{ bind_config }}
  become: true
  ansible.builtin.template:
    src: etc/named.conf.j2
    dest: "{{ bind_config }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0640
    backup: true
    validate: 'named-checkconf %s'
  notify:
    # - validate configuration
    - reload bind

...
