---

- name: do facts module to get latest information
  ansible.builtin.setup:
    gather_subset:
      - 'network'
      - 'all_ipv4_addresses'
      - 'all_ipv6_addresses'

- name: define a list of all host IP addresses
  ansible.builtin.set_fact:
    host_all_addresses: "{{ ansible_facts.all_ipv4_addresses | union(ansible_facts.all_ipv6_addresses) }}"
  tags: bind

- name: create bind zone files
  bodsch.dns.bind_zone_files:
    zones: "{{ bind_zones }}"
    zone_directory: "{{ bind_zone_dir }}"
    serial_strategy: "increment"
  notify: reload bind

...
