---

- name: restart unbound
  ansible.builtin.service:
    name: unbound
    state: restarted

- name: disable systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
  ignore_errors: true
  register: systemd_resolved
  failed_when: systemd_resolved.rc != 0
  when:
    - systemd_resolved_unit_file is defined
    - systemd_resolved_unit_file | string | length > 0
