---

# - name: prepare database
#   hosts: database
#   gather_facts: true
#
#   roles:
#     - role: bodsch.mariadb

- name: converge
  hosts: instance
  any_errors_fatal: true
  gather_facts: true

  environment:
    NETRC: ''

  roles:
    - role: bodsch.dns.pdns
