---

bind_statistics:
  channels: true
  allow:
    - any
  host: "127.0.0.1"

bind_allow_query:
  - any

bind_dns_keys:
  - name: primary_key
    algorithm: hmac-sha256
    secret: "azertyAZERTY123456"
  - name: primary-dns
    algorithm: hmac-sha256
    secret: "Rz6sUQHdTG7MMv3w608TZYig"

bind_listen:
  ipv4:
    - port: 53
      addresses:
        - "127.0.0.1"
        - "10.11.0.1"
    - port: 5353
      addresses:
        - "127.0.1.1"
  # ipv6:
  #   - port: 53
  #     addresses:
  #       - "{{ ansible_default_ipv6.address }}"

bind_acls:
  - name: acl1
    match_list:
      - 10.11.0.0/24

bind_forwarders:
  - '9.9.9.9'
  - '141.1.1.1'

bind_recursion: true
bind_dns64: true

bind_check_names:
  - master
  - ignore

bind_logging:
  enable: true
  channels:
    - channel: general
      file: "data/general.log"
      versions: 3
      size: 10M
      print_time: true           # true | false
      print_category: true
      print_severity: true
      severity: dynamic          # critical | error | warning | notice | info | debug [level] | dynamic
    - channel: query
      file: "data/query.log"
      versions: 5
      size: 10M
      print_time: ""               # true | false
      severity: debug2             #
    - channel: dnssec
      file: "data/dnssec.log"
      versions: 5
      size: 10M
      print_time: ""               # true | false
      severity: info               #
    - channel: notify
      file: "data/notify.log"
      versions: 5
      size: 10M
      print_time: ""               # true | false
      severity: info               #
    - channel: transfers
      file: "data/transfers.log"
      versions: 5
      size: 10M
      print_time: ""               # true | false
      severity: info               #
    - channel: slog
      syslog: security             # kern | user | mail | daemon | auth | syslog | lpr |
                                   # news | uucp | cron | authpriv | ftp |
                                   # local0 | local1 | local2 | local3 |
                                   # local4 | local5 | local6 | local7
      print_time: ""               # true | false
      severity: info               #
  categories:
    "xfer-out":
      - transfers
      - slog
    "xfer-in":
      - transfers
      - slog
    notify:
      - notify
    "lame-servers":
      - general
    config:
      - general
    default:
      - general
    security:
      - general
      - slog
    dnssec:
      - dnssec
    queries:
      - query

bind_zone_soa:
  minimum_ttl: "32H"
  ttl: "48H"
  time_to_refresh: "24H"
  time_to_retry: "2H"
  time_to_expire: "2D"

bind_zones:
  - name: 'acme-inc.com'
    type: primary
    create_forward_zones: true
    create_reverse_zones: true
    #primaries:
    #  - 10.11.0.1
    networks:
      - '10.11.0'
    ipv6_networks:
      - '2001:db8::/48'
    name_servers:
      - ns1
      - ns2
    #
    allow_updates:
      - "10.0.1.2"
      - 'key "external-dns"'
    allow_transfers:
      - 'key "external-dns"'

    hosts:
      - name: ns1
        ip: 10.11.0.1
      - name: ns2
        ip: 10.11.0.2
      - name: srv001
        ip: 10.11.1.1
        ipv6: 2001:db8::1
        aliases:
          - www
      - name: srv002
        ip: 10.11.1.2
        ipv6: 2001:db8::2
        aliases:
          - mysql
      - name: mail001
        ip: 10.11.2.1
        ipv6: 2001:db8::d:1
        aliases:
          - smtp
          - mail-in
      - name: mail002
        ip: 10.11.2.2
        ipv6: 2001:db8::d:2
      - name: mail003
        ip: 10.11.2.3
        ipv6: 2001:db8::d:3
        aliases:
          - imap
          - mail-out
      - name: srv010
        ip: 10.11.0.10
      - name: srv011
        ip: 10.11.0.11
      - name: srv012
        ip: 10.11.0.12
    mail_servers:
      - name: mail001
        preference: 10
      - name: mail002
        preference: 20
    services:
      - name: _ldap._tcp
        weight: 100
        port: 88
        target: srv010
    text:
      - name: _kerberos
        text: KERBEROS.ACME-INC.COM
      - name: '@'
        text:
          - 'some text'
          - 'more text'

  - name: cm.local
    # type: primary               # default: primary [primary, secondary, forward]
    # create_forward_zones: true
    # create_reverse_zones: true  # Skip creation of reverse zones
    primaries:
      - "{{ ansible_default_ipv4.address }}" # Primary server(s) for this zone
    name_servers:
      - 'dns'
    networks:
      - '192.168.124'
    hosts:
      - name: '@'
        name_servers: 'dns.cm.local.'
        ip: "{{ ansible_default_ipv4.address }}"
      - name: dns
        ip: "{{ ansible_default_ipv4.address }}"
      - name: cms
        ip: 192.168.124.21
        aliases:
          - content-management-server
      - name: mls
        ip: 192.168.124.30
        aliases:
          - master-live-server
      - name: rls-01
        ip: 192.168.124.35
        aliases:
          - replication-live-server-01

  # - name: matrix.local
  #   type: primary
  #   create_reverse_zones: true  # Skip creation of reverse zones
  #   primaries:
  #     - "{{ ansible_default_ipv4.address }}" # Primary server(s) for this zone
  #   name_servers:
  #     - 'dns'
  #   networks:
  #     - '192.168.111'
  #   ipv6_networks:
  #     - '2001:0db8:85a3::8a2e:0370:7334/48'
  #   hosts:
  #     - name: '@'
  #       name_servers: 'dns.cm.local.'
  #       ip: "{{ ansible_default_ipv4.address }}"

...
