---

pihole_admin_password: "SuperSicher2024!"
pihole_dns_1: "1.1.1.1"          # Cloudflare
pihole_dns_2: "9.9.9.9"          # Quad9
pihole_dnssec: true
configure_firewall: true

pihole_groups:
  - name: admin
    description: "Admin Group"
    enabled: true
  - name: kids
    description: "Kids only"
    enabled: true

# Zusätzliche Blocklisten
pihole_custom_denylists:
  - address: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  #
  - address: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
  - address: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
  - address: https://v.firebog.net/hosts/static/w3kbl.txt
  - address: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
  - address: https://someonewhocares.org/hosts/zero/hosts
  - address: https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
  - address: https://winhelp2002.mvps.org/hosts.txt
  - address: https://v.firebog.net/hosts/neohostsbasic.txt
  - address: https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
  - address: https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
  #
  - address: https://adaway.org/hosts.txt
  - address: https://v.firebog.net/hosts/AdguardDNS.txt
  - address: https://v.firebog.net/hosts/Admiral.txt
  - address: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  - address: https://v.firebog.net/hosts/Easylist.txt
  - address: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  - address: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  - address: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  #
  - address: https://v.firebog.net/hosts/Easyprivacy.txt
  - address: https://v.firebog.net/hosts/Prigent-Ads.txt
  - address: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
  - address: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  - address: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
  - address: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
  - address: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
  - address: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
  - address: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
  #
  - address: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  - address: https://v.firebog.net/hosts/Prigent-Crypto.txt
  - address: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  - address: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  - address: https://phishing.army/download/phishing_army_blocklist_extended.txt
  - address: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  - address: https://v.firebog.net/hosts/RPiList-Malware.txt
  - address: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  - address: https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
  - address: https://urlhaus.abuse.ch/downloads/hostfile/
  - address: https://lists.cyberhost.uk/malware.txt
  - address: https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
  - address: https://v.firebog.net/hosts/Prigent-Malware.txt
  - address: https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/wildcard_domains/scams.txt
  - address: https://v.firebog.net/hosts/RPiList-Phishing.txt
  # - address: "https://someonewhocares.org/hosts/zero/hosts"
  #   enabled: false
  # - address: "https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt"
  #   enabled: false
  # - address: "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt"
  #   enabled: false
  # - address: "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt"
  #   enabled: false

# Wichtige Domains freigeben
pihole_domain_allowlist:
  # Microsoft Updates
  - "delivery.mp.microsoft.com"
  - "tlu.dl.delivery.mp.microsoft.com" 
  - "download.windowsupdate.com"
  # Google Services (für manche Seiten nötig)
  - "googleadservices.com"
  - "googlesyndication.com"
  # Social Media APIs
  - "graph.facebook.com"
  - "scontent.xx.fbcdn.net"
  # Streaming
  - "widget-cdn.rpxnow.com"
  - "secure.netflix.com"
  # Gaming
  - "clientconfig.rpx.ol.epicgames.com"

# Zusätzlich blockieren
pihole_domain_denylist:
  # Tracking
  - "google-analytics.com"
  - "googletagmanager.com"
  - "hotjar.com"
  - "mouseflow.com"
  # Social Media (optional)
  - "tiktok.com"
  # Werbung
  - "outbrain.com"
  - "taboola.com"
