---
# https://doc.powerdns.com/authoritative/backends/lmdb.html

- name: define lmdb backend data
  ansible.builtin.set_fact:
    _pdns_backend_data: "{{ pdns_backends | bodsch.dns.pdns_backend_data('lmdb') }}"

- name: create directory for lmdb database
  ansible.builtin.file:
    name: "{{ _pdns_backend_data[0].filename | dirname }}"
    owner: "{{ pdns_owner }}"
    group: "{{ pdns_group }}"
    state: directory
    mode: "0750"
