---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: arch- / artixlinux
      when:
        - ansible_distribution | lower == 'archlinux' or
          ansible_os_family | lower == 'artix linux'
      block:
        - name: update pacman system
          ansible.builtin.command: |
            pacman --refresh --sync --sysupgrade --noconfirm

        - name: create depends service
          ansible.builtin.copy:
            mode: 0755
            dest: /etc/init.d/net
            content: |
              #!/usr/bin/openrc-run
              true
          when:
            - ansible_os_family | lower == 'artix linux'

    - name: update package cache
      ansible.builtin.package:
        update_cache: true

    - name: install dependency
      ansible.builtin.package:
        name:
          - iproute2
          - bind9-dnsutils
        state: present

    - name: environment
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

- name: install bertvv.bind
  hosts: all
  gather_facts: true

  vars:
    ansible_all_ipv4_addresses: []
    bind_dnssec_enable: false
    bind_check_names: 'master ignore'

  pre_tasks:
    - name: do facts module to get latest information
      ansible.builtin.setup:
        gather_subset:
          - 'all'

  roles:
    - role: bertvv.bind

...
