---

- name: user and group handling
  when:
    - knot_resolver_owner != "root"
  block:
    - name: create kresd group
      ansible.builtin.group:
        name: "{{ knot_resolver_group }}"
        state: present
        system: true

    - name: create kresd user
      ansible.builtin.user:
        name: "{{ knot_resolver_owner }}"
        groups: "{{ knot_resolver_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: merge knot_resolver configuration between defaults and custom
  ansible.builtin.set_fact:
    knot_resolver_cache: "{{ knot_resolver_defaults_cache | combine(knot_resolver_cache, recursive=True) }}"
    knot_resolver_log: "{{ knot_resolver_defaults_log | combine(knot_resolver_log, recursive=True) }}"
    knot_resolver_prometheus: "{{ knot_resolver_defaults_prometheus | combine(knot_resolver_prometheus, recursive=True) }}"
    knot_resolver_predict: "{{ knot_resolver_defaults_predict | combine(knot_resolver_predict, recursive=True) }}"
    knot_resolver_service: "{{ knot_resolver_systemd.unit | bodsch.dns.knot_resolver_service(
        os_family=ansible_facts.os_family,
        count=knot_resolver_systemd.instances | default(0),
        service='kresd@.service') }}"

- name: create knot resolver configuration
  ansible.builtin.template:
    src: kresd.conf.j2
    dest: /etc/knot-resolver/kresd.conf
    mode: "0664"
    backup: true
  notify:
    - restart kresd

- name: openrc
  when:
    - ansible_facts.service_mgr | lower == 'openrc'
  block:
    - name: create kres-cache-gc config
      ansible.builtin.template:
        src: init/openrc/conf.d/kres-cache-gc.j2
        dest: /etc/conf.d/kres-cache-gc
        mode: "0640"
      notify:
        - restart kres-cache-gc

    - name: create kresd config
      ansible.builtin.template:
        src: init/openrc/conf.d/kresd.j2
        dest: /etc/conf.d/kresd
        mode: "0640"
      notify:
        - restart kresd

...
