---

- name: install knot resolver packages
  ansible.builtin.package:
    name: "{{ knot_resolver_packages }}"
    state: present

- name: openrc
  when:
    - ansible_facts.service_mgr | lower == 'openrc'
  block:
    - name: create kres-cache-gc init script
      ansible.builtin.template:
        src: init/openrc/init.d/kres-cache-gc.j2
        dest: /etc/init.d/kres-cache-gc
        mode: "0755"

    - name: create kresd  init script
      ansible.builtin.template:
        src: init/openrc/init.d/kresd.j2
        dest: /etc/init.d/kresd
        mode: "0755"

- name: update trusted-key
  bodsch.dns.kdig:
    root_dns: "{{ knot_resolver_trusted.dns_server | default('k.root-servers.net') }}"
    signing_key: "{{ knot_resolver_trusted.signing_key | default('257') | int }}"
    trust_keyfile: "{{ knot_resolver_trusted.keyfile | default('/etc/trusted-key.key') }}"
  notify:
    - restart kresd

...
