---

- name: debain based
  when:
    - ansible_os_family | lower == 'debian'
  block:
    - name: download CZ.NIC gpg key and save as keyring
      ansible.builtin.get_url:
        url: https://pkg.labs.nic.cz/gpg
        dest: /usr/share/keyrings/cznic-labs-pkg.gpg
        mode: '0644'

    - name: add CZ.NIC apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cznic-labs-pkg.gpg] https://pkg.labs.nic.cz/knot-resolver bookworm main"
        filename: "cznic-labs-knot-resolver.list"
        state: present
        update_cache: true

- name: update package cache
  ansible.builtin.package:
    update_cache: true

...
