---

- name: start and enable Knot Resolver service (systemd)
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ knot_resolver_service }}"
  when:
    - ansible_facts.service_mgr | lower == 'systemd'

- name: start and enable Knot Resolver service (openrc)
  ansible.builtin.service:
    name: kresd
    state: started
    enabled: true
  when:
    - ansible_facts.service_mgr | lower == 'openrc'

...
