---

# - block:
#
#   - name: Ensure the override directory exists (systemd)
#     file:
#       name: "/etc/systemd/system/{{ pdns_service_name }}.service.d"
#       state: directory
#       owner: root
#       group: root
#
#   - name: Override the PowerDNS Authoritative Server unit (systemd)
#     template:
#       src: "override-service.systemd.conf.j2"
#       dest: "/etc/systemd/system/{{ pdns_service_name }}.service.d/override.conf"
#       owner: root
#       group: root
#     register: _pdns_override_unit
#     when: pdns_service_overrides | length > 0
#
#   - name: Reload systemd
#     systemd:
#       daemon_restart: yes
#     when: not pdns_disable_handlers
#       and _pdns_override_unit.changed
#
#   when: ansible_service_mgr == "systemd"

- name: create directory for pdns configuration
  ansible.builtin.file:
    name: "{{ pdns_config_dir }}"
    state: directory
    owner: "{{ pdns_file_owner }}"
    group: "{{ pdns_file_group }}"
    mode: "0750"

- name: create directory for pdns 'include-dir'
  ansible.builtin.file:
    name: "{{ pdns_config_include }}"
    state: directory
    owner: "{{ pdns_file_owner }}"
    group: "{{ pdns_file_group }}"
    mode: "0750"
  when:
    - pdns_config_include is defined

- name: generate the pdns backend configuration
  ansible.builtin.template:
    src: "{{ item }}.conf.j2"
    dest: "{{ pdns_config_include }}/{{ item }}.conf"
    owner: "{{ pdns_file_owner }}"
    group: "{{ pdns_file_group }}"
    mode: "0644"
    backup: true
  loop:
    - pdns_general
    - pdns_backends
    - pdns_webserver
  notify:
    - restart pdns

- name: generate the pdns configuration
  ansible.builtin.template:
    src: pdns.conf.j2
    dest: "{{ pdns_config_dir }}/{{ pdns_config_file }}"
    owner: "{{ pdns_file_owner }}"
    group: "{{ pdns_file_group }}"
    mode: "0640"
    backup: true
  notify:
    - restart pdns
#  register: _pdns_configuration


# - name: Restart PowerDNS
#   ansible.builtin.service:
#     name: "{{ pdns_service_name }}"
#     state: restarted
#     sleep: 1
#   when: not pdns_disable_handlers
#     and pdns_service_state != 'stopped'
#     and (_pdns_override_unit.changed
#       or _pdns_configuration.changed)
