---

- name: create directory for pdns configuration
  ansible.builtin.file:
    name: "{{ pdns_config_dir }}"
    state: directory
    owner: "{{ pdns_file_owner }}"
    group: "{{ pdns_file_group }}"
    mode: "0750"

- name: create directory for pdns 'include-dir'
  ansible.builtin.file:
    name: "{{ pdns_config_include }}"
    state: directory
    owner: "{{ pdns_file_owner }}"
    group: "{{ pdns_file_group }}"
    mode: "0750"
  when:
    - pdns_config_include is defined

- name: generate the pdns configuration files
  ansible.builtin.template:
    src: "{{ item }}.conf.j2"
    dest: "{{ pdns_config_include }}/{{ item }}.conf"
    owner: "{{ pdns_file_owner }}"
    group: "{{ pdns_file_group }}"
    mode: "0644"
    backup: true
  loop:
    - pdns_general
    - pdns_backends
    - pdns_webserver
    - pdns_api
  notify:
    - restart pdns

- name: remove built-in pdns backend bind configuration
  ansible.builtin.file:
    dest: "{{ pdns_config_include }}/bind.conf"
    state: absent
  notify:
    - restart pdns

- name: remove built-in pdns backend lmdb configuration
  ansible.builtin.file:
    dest: "{{ pdns_config_include }}/lmdb.conf"
    state: absent
  notify:
    - restart pdns

- name: generate the pdns configuration
  ansible.builtin.template:
    src: pdns.conf.j2
    dest: "{{ pdns_config_dir }}/pdns.conf"
    owner: "{{ pdns_file_owner }}"
    group: "{{ pdns_file_group }}"
    mode: "0640"
    backup: true
  notify:
    - restart pdns
