---

- name: install pdns
  become: true
  package:
    name: "{{ pdns_packages }}"
    state: present

- name: detect pdns version
  become: true
  bodsch.dns.pdns_version:
  register: pdns_version
  check_mode: false
  ignore_errors: true

- name: create custom fact file
  bodsch.core.facts:
    name: pdns
    facts:
      full_version: "{{ pdns_version.full_version }}"
      version: "{{ pdns_version.version }}"

