---

- name: repositories
  ansible.builtin.include_tasks: repositories/debian.yml
  when:
    - ansible_os_family | lower == 'debian'
    - pdns_external_repo | default('false') | bool

- name: install pdns
  become: true
  package:
    name: "{{ pdns_packages }}"
    state: present

- name: detect pdns version
  become: true
  bodsch.dns.pdns_version:
  register: pdns_version
  check_mode: false
  ignore_errors: true

- name: create custom fact file
  bodsch.core.facts:
    name: pdns
    facts:
      full_version: "{{ pdns_version.full_version }}"
      version: "{{ pdns_version.version }}"

# -----------------------------------------------------------------

- name: systemd
  when:
    - ansible_service_mgr == "systemd"
  block:
    - name: populate service facts
      ansible.builtin.service_facts:
      register: systemd_facts
      no_log: true
      tags:
        - pdns
        - install

    - name: set systemd unit name
      ansible.builtin.set_fact:
        resolved_unit_file: "{{ ansible_facts.services | bodsch.systemd.service('systemd-resolved', state='running') }}"
      tags:
        - pdns
        - install

    - name: disable systemd-resolved
      service:
        name: "{{ resolved_unit_file }}"
        state: stopped
        enabled: false
      when:
        - resolved_unit_file | default('') | string | length > 0
