---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: install
  ansible.builtin.include_tasks: install.yml

- name: install
  ansible.builtin.include_tasks: database/main.yml

- name: configure
  ansible.builtin.include_tasks: configure.yml

- name: service
  ansible.builtin.include_tasks: service.yml

- name: domains
  ansible.builtin.include_tasks: domains.yml

...
