---

- name: add CZ.NIC apt sources
  when:
    - ansible_facts.os_family | lower == 'debian'
  bodsch.core.apt_sources:
    name: cznic-labs-knot-dns
    filename: cznic-labs-knot-dns.sources
    uris:
      - https://pkg.labs.nic.cz/knot-dns
    suites: "{{ ansible_facts.distribution_release | lower }}"
    components:
      - main
    signed_by: /usr/share/keyrings/cznic-labs-pkg.gpg
    key:
      method: download
      url: "https://pkg.labs.nic.cz/gpg"
      dest: "/usr/share/keyrings/cznic-labs-pkg.gpg"
      dearmor: true
      validate: true
    update_cache: true

- name: add knot ppa for ubuntu {{ ansible_facts.distribution_release }}
  when:
    - ansible_facts.distribution | lower == 'ubuntu'
  ansible.builtin.apt_repository:
    repo: ppa:cz.nic-labs/knot-dns-latest
    codename: "{{ ansible_facts.distribution_release }}"
    state: present
    update_cache: true
    validate_certs: false

- name: update package cache
  ansible.builtin.package:
    update_cache: true

...
