---

bind_statistics:
  channels: true
  allow:
    - any
  host: "{{ ansible_default_ipv4.address }}"

bind_zone_dir: /var/local/named-zones
bind_zone_file_mode: '0660'

bind_allow_query:
  - any

bind_listen:
  ipv4:
    - port: 53
      addresses:
        - "127.0.0.1"
        - "{{ ansible_default_ipv4.address }}"
    - port: 5353
      addresses:
        - "127.0.1.1"
  ipv6:
    - port: 53
      addresses:
        - "{{ ansible_default_ipv4.address }}"

bind_acls:
  - name: acl1
    match_list:
      - 10.11.0.0/16

bind_forwarders:
  - '9.9.9.9'
  - '141.1.1.1'

bind_recursion: true
bind_dns64: true
# bind_query_log: 'data/query.log'
bind_check_names: 'master ignore'

bind_zone:
  minimum_ttl: "2D"
  ttl: "2W"
  time_to_refresh: "2D"
  time_to_retry: "2H"
  time_to_expire: "2W"

# bind_query_log:
#   enable: true
#   file: data/query.log
#   versions: 100
#   size: 10m

bind_zones:
  - name: 'molecule.lan'
    primaries:
      - "{{ ansible_default_ipv4.address }}" # Primary server(s) for this zone
    networks:
      - '172.17'
    name_servers:
      - ns1.acme-inc.com.
      - ns2.acme-inc.com.
    hostmaster_email: admin
    hosts:
      - name: srv001
        ip: 172.17.2.1
        aliases:
          - www
      - name: srv002
        ip: 172.17.2.2

  - name: matrix.vpn
    # create_reverse_zones: true  # Skip creation of reverse zones
    # type: primary
    hostmaster_email: admin
    primaries:
      - "{{ ansible_default_ipv4.address }}" # Primary server(s) for this zone
    name_servers:
      - 'dns.matrix.lan.'
    networks:
      - '172.10.0'
    mail_servers:
      - name: mx
        preference: 10
    hosts:
      - name: '@'
        name_servers: 'dns.matrix.lan.'
        ip: "{{ ansible_default_ipv4.address }}"
      - name: dns
        ip: "{{ ansible_default_ipv4.address }}"
        ttl: 3600
      - name: www
        ip: 172.10.0.11
      - name: mail
        ip: 172.10.0.12
      - name: ldap
        ip: 172.10.0.13
    # services:
    #   - name: _ldap._tcp
    #     weight: 100
    #     port: 88
    #     target: ldap
    # text:
    #   - name: _sshd
    #     text: "ssh-rsa AAAABxxx....63x foo@bar.com"
    #   - name: '@'
    #     text:
    #       - 'some text'
    #       - 'more text'

  # - name: 'example.com'
  #   primaries:
  #     - 10.11.0.4
  #   networks:
  #     - '192.0.2'
  #   ipv6_networks:
  #     - '2001:db9::/48'
  #   name_servers:
  #     - ns1.acme-inc.com.
  #     - ns2.acme-inc.com.
  #   hostmaster_email: admin.example.com
  #   hosts:
  #     - name: srv001
  #       ip: 192.0.2.1
  #       ipv6: '2001:db9::1'
  #       aliases:
  #         - www
  #     - name: srv002
  #       ip: 192.0.2.2
  #       ipv6: '2001:db9::2'
  #     - name: mail001
  #       ip: 192.0.2.10
  #       ipv6: '2001:db9::3'
  #   mail_servers:
  #     - name: mail001
  #       preference: 10
  #
  # - name: 'acme-inc.com'
  #   primaries:
  #     - 10.11.0.4
  #   networks:
  #     - '10.11'
  #   name_servers:
  #     - ns1
  #     - ns2
  #   hosts:
  #     - name: ns1
  #       ip: 10.11.0.4
  #     - name: ns2
  #       ip: 10.11.0.5
  #     - name: srv001
  #       ip: 10.11.1.1
  #       aliases:
  #         - www
  #     - name: srv002
  #       ip: 10.11.1.2
  #       aliases:
  #         - mysql
  #     - name: mail001
  #       ip: 10.11.2.1
  #       aliases:
  #         - smtp
  #         - mail-in
  #     - name: mail002
  #       ip: 10.11.2.2
  #     - name: mail003
  #       ip: 10.11.2.3
  #       aliases:
  #         - imap
  #         - mail-out
  #     - name: srv010
  #       ip: 10.11.0.10
  #     - name: srv011
  #       ip: 10.11.0.11
  #     - name: srv012
  #       ip: 10.11.0.12
  #   mail_servers:
  #     - name: mail001
  #       preference: 10
  #     - name: mail002
  #       preference: 20
  #   services:
  #     - name: _ldap._tcp
  #       weight: 100
  #       port: 88
  #       target: srv010
  #   text:
  #     - name: _kerberos
  #       text: KERBEROS.ACME-INC.COM
  #     - name: '@'
  #       text:
  #         - 'some text'
  #         - 'more text'
  #
  # # Example of a primary zone (hosts: and name_servers: ares defined)
  # - name: mydomain.com           # Domain name
  #   create_reverse_zones: false  # Skip creation of reverse zones
  #   primaries:
  #     - 192.0.2.1                # Primary server(s) for this zone
  #   name_servers:
  #     - pub01.mydomain.com.
  #     - pub02.mydomain.com.
  #   hosts:
  #     - name: pub01
  #       ip: 192.0.2.1
  #       ipv6: 2001:db8::1
  #       aliases:
  #         - ns1
  #     - name: pub02
  #       ip: 192.0.2.2
  #       ipv6: 2001:db8::2
  #       aliases:
  #         - ns2
  #     - name: '@'                # Enables "http://mydomain.com/"
  #       ip:
  #         - 192.0.2.3            # Multiple IP addresses for a single host
  #         - 192.0.2.4            #   results in DNS round robin
  #       sshfp:                   # Secure shell fingerprint
  #         - "3 1 1262006f9a45bb36b1aa14f45f354b694b77d7c3"
  #         - "3 2 e5921564252fe10d2dbafeb243733ed8b1d165b8fa6d5a0e29198e5793f0623b"
  #       ipv6:
  #         - 2001:db8::2
  #         - 2001:db8::3
  #       aliases:
  #         - www
  #     - name: priv01             # This IP is in another subnet, will result in
  #       ip: 10.0.0.1             #   multiple reverse zones
  #     - name: mydomain.net.
  #       aliases:
  #         - name: sub01
  #           type: DNAME          # Example of a DNAME alias record
  #   networks:
  #     - '192.0.2'
  #     - '10'
  #     - '172.16'
  #   delegate:
  #     - zone: foo
  #       dns: 192.0.2.1
  #   services:
  #     - name: _ldap._tcp
  #       weight: 100
  #       port: 88
  #       target: dc001
  #   naptr:                       # Name Authority Pointer record, used for IP
  #     - name: "sip"              #   telephony
  #       order: 100
  #       pref: 10
  #       flags: "S"
  #       service: "SIP+D2T"
  #       regex: "!^.*$!sip:customer-service@example.com!"
  #       replacement: "_sip._tcp.example.com."
  #
  # # Minimal example of a secondary zone
  # - name: acme.com
  #   primaries:
  #     - 172.17.0.2
  #   networks:
  #     - "172.17"
  # # Minimal example of a forward zone
  # - name: acme.com
  #   forwarders:
  #     - 172.17.0.2
  #   networks:
  #     - "172.17"

...
