---

- name: restart pihole-FTL
  ansible.builtin.systemd:
    name: pihole-FTL
    state: restarted

- name:  pihole update gravity
  bodsch.dns.pihole_command:
    command: update_gravity
  register: gravity_result

- name:  pihole reload lists
  bodsch.dns.pihole_command:
    command: reloadlists
  register: reload_result
