---

galaxy_info:
  role_name: bind

  author: Bodo Schulz
  description: ansible role for install and configure isc bind server

  license: Apache
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        # 11
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        # 20.04
        - focal

  galaxy_tags:
    - system
    - dns

dependencies: []

...
