---

pihole_delegate_to: localhost

pihole_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/pihole', true) }}/{{ pihole_version }}"

pihole_cache_directory: /var/cache/ansible/pihole

pihole_remote_tmp_directory: "{{ pihole_cache_directory }}/{{ pihole_version }}"

pihole_dependencies:
  - dnsutils
  - net-tools
  - python3-toml

pihole_defaults_config:
  dns:
    upstreams:
      - '1.1.1.1'
      - '1.0.0.1'
      - '9.9.9.9'
    CNAMEdeepInspect: true
    blockESNI: true
    EDNS0ECS: true
    ignoreLocalhost: false
    showDNSSEC: true
    analyzeOnlyAandAAAA: false
    piholePTR: PI.HOLE
    replyWhenBusy: ALLOW
    blockTTL: 2
    domainNeeded: false
    expandHosts: false
    domain: pi.hole
    bogusPriv: true
    dnssec: false
    interface: "{{ ansible_default_ipv4.interface }}"
    listeningMode: LOCAL
    queryLogging: true
    port: 53
    cache:
      size: 10000
      optimizer: 3600
      upstreamBlockedTTL: 86400
    blocking:
      active: true
      mode: NULL
      edns: TEXT
    specialDomains:
      mozillaCanary: true
      iCloudPrivateRelay: true
      designatedResolver: true
    reply:
      host:
        force4: false
        force6: false
      blocking:
        force4: false
        force6: false
    rateLimit:
      count: 1000
      interval: 60
  dhcp:
    active: false
    ipv6: false
    rapidCommit: false
    multiDNS: false
    logging: false
    ignoreUnknownClients: false
  ntp:
    ipv4:
      active: true
    ipv6:
      active: true
    sync:
      active: true
      server: pool.ntp.org
      interval: 3600
      count: 8
      rtc:
        set: false
        utc: true
  resolver:
    resolveIPv4: true
    resolveIPv6: true
    networkNames: true
    refreshNames: IPV4_ONLY
  database:
    DBimport: true
    maxDBdays: 91
    DBinterval: 60
    useWAL: true
    network:
      parseARPcache: true
      expire: 91
  webserver:
    domain: pi.hole
    port: 80
    threads: 50
    headers:
      - 'X-DNS-Prefetch-Control: off'
      - "Content-Security-Policy: default-src 'self' 'unsafe-inline';"
      - 'X-Frame-Options: DENY'
      - 'X-XSS-Protection: 0'
      - 'X-Content-Type-Options: nosniff'
      - 'Referrer-Policy: strict-origin-when-cross-origin'
    serve_all: false
    session:
      timeout: 3200
      restore: true
    tls:
      cert: /etc/pihole/tls.pem
    paths:
      webroot: /var/www/html
      webhome: /admin/
    interface:
      boxed: true
      theme: default-light
    api:
      max_sessions: 16
      prettyJSON: true
      pwhash: $BALLOON-SHA256$v=1$s=1024,t=32$RSqXeRU/3QMJIAVOw0jvRA==$SlkKXw2Xhq5Y0OlnGiH+BOpm0MPdPYn3vgXHqucnRjg=
      app_sudo: false
      cli_pw: true
      maxHistory: 86400
      maxClients: 10
      client_history_global_max: true
      allow_destructive: true
      temp:
        limit: 60.0
        unit: C
  files:
    pid: /run/pihole-FTL.pid
    database: /etc/pihole/pihole-FTL.db
    gravity: /etc/pihole/gravity.db
    gravity_tmp: /var/tmp
    macvendor: /etc/pihole/macvendor.db
    log:
      ftl: /var/log/pihole/FTL.log
      dnsmasq: /var/log/pihole/pihole.log
      webserver: /var/log/pihole/webserver.log
  misc:
    privacylevel: 0
    delay_startup: 10
    nice: -10
    addr2line: true
    etc_dnsmasq_d: false
    extraLogging: false
    readOnly: false
    check:
      load: true
      shmem: 90
      disk: 90
  debug:
    database: false
    networking: false
    locks: false
    queries: false
    flags: false
    shmem: false
    gc: false
    arp: false
    regex: false
    api: false
    tls: false
    overtime: false
    status: false
    caps: false
    dnssec: false
    vectors: false
    resolver: false
    edns0: false
    clients: false
    aliasclients: false
    events: false
    helper: false
    config: false
    inotify: false
    webserver: false
    extra: false
    reserved: false
    ntp: false
    netlink: false
    all: false

...
