---

pihole_delegate_to: localhost

pihole_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/pihole', true) }}/{{ pihole_version }}"

pihole_cache_directory: /var/cache/ansible/pihole

pihole_remote_tmp_directory: "{{ pihole_cache_directory }}/{{ pihole_version }}"

pihole_dependencies:
  #- curl
  #- wget
  #- ca-certificates
  - dnsutils
  - net-tools
  - python-toml

...
