---

- name: Set the status of the PowerDNS Recursor service
  service:
    name: "{{ pdns_recursor_service_name }}"
    state: "{{ pdns_recursor_service_state }}"
    enabled: "{{ pdns_recursor_service_enabled }}"
  tags:
    - service

...
