---

galaxy_info:
  role_name: fqdn

  author: Bodo Schulz
  description: ansible role for managing FQDN information.

  license: Apache
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        # 20.04
        - focal
        # 22.04
        - jammy

  galaxy_tags:
    - system
    - dns
    - networking

dependencies: []

...
