---

# - name: Install gnupg
#   ansible.builtin.package:
#     name: gnupg
#     state: present

- name: add apt signing key
  ansible.builtin.apt_key:
    url: https://repo.powerdns.com/CBC8B383-pub.asc
    # id: "{{ pdns_install_repo['gpg_key_id'] | default('') }}"
    state: present
  register: apt_key
  changed_when: apt_key.changed
  failed_when: apt_key.failed

- name: Add the PowerDNS APT Repository
  ansible.builtin.apt_repository:
    # filename: "{{ pdns_install_repo['name'] }}"
    repo: deb [signed-by=/etc/apt/keyrings/auth-master-pub.asc] http://repo.powerdns.com/debian bookworm-auth-master main
    state: present
  register: apt_repo
  changed_when: apt_repo.changed
  failed_when: apt_repo.failed

- name: Update the APT cache
  ansible.builtin.apt:
    update_cache: true
  when:
    - apt_key.changed or _pdns_apt_repo.changed

# - name: Pin the PowerDNS APT Repository
#   ansible.builtin.template:
#     src: pdns.pin.j2
#     dest: /etc/apt/preferences.d/pdns
#     owner: root
#     group: root
#     mode: 0644
