---

pdns_backends:
  - name: lmdb
    filename: /var/lib/powerdns/pdns.lmdb
    shards: 64
    sync-mode: nometasync
    # schema-version: 5
    random-ids: true
    map-size: 16000
    # flag-deleted:
    # lightning-stream:

pdns_config:
  master: true
  slave: false
  also-notify: ""
  local-address: '127.0.0.1'
  local-port: '5300'
  log-dns-details: true
  loglevel: "5"   # 0 = emergency, 1 = alert, 2 = critical, 3 = error, 4 = warning, 5 = notice, 6 = info, 7 = debug

pdns_webserver:
  enabled: true
  address: "{{ ansible_default_ipv4.address }}"
  allow-from:
    - "127.0.0.1"
    - "::1"
    - "10.11.0.0/24"
    - "192.168.0.0/24"
  connection-timeout: 5
  hash-plaintext-credentials: false
  loglevel: normal
  max-bodysize: 2
  password:
  port: 8081
  print-arguments: true

pdns_api:
  enabled: true
  key: tNSN-E1FxeDe/3nhqA

...
