---

bind_statistics:
  channels: true
  allow:
    - any
  host: "{{ ansible_default_ipv4.address }}"

bind_allow_query:
  - any

bind_listen:
  ipv4:
    - port: 53
      addresses:
        - "127.0.0.1"
        - "{{ ansible_default_ipv4.address }}"
    - port: 5353
      addresses:
        - "127.0.1.1"
  ipv6:
    - port: 53
      addresses:
        - "{{ ansible_default_ipv4.address }}"

bind_acls:
  - name: acl1
    match_list:
      - 10.11.0/24

bind_forwarders:
  - '9.9.9.9'
  - '141.1.1.1'

bind_recursion: true
bind_dns64: true

bind_check_names:
  - master
  - ignore

bind_zone_soa:
  minimum_ttl: "32H"
  ttl: "48H"
  time_to_refresh: "24H"
  time_to_retry: "2H"
  time_to_expire: "2D"

...
