---

galaxy_info:
  role_name: pdns_records

  author: Bodo Schulz
  description: Ansible role for create dns records for powerdns

  license: Apache
  min_ansible_version: "2.12"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 11
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        # 20.04
        - focal

  galaxy_tags:
    - system
    - dns
    - pdns
    - powerdns
