---

- name: install bind
  become: true
  ansible.builtin.package:
    name: "{{ bind_packages }}"
    state: present
  tags:
    - bind

- name: detect bind version
  become: true
  bodsch.dns.bind_version:
  register: bind_version
  check_mode: false
  ignore_errors: true

- name: create custom fact file
  bodsch.core.facts:
    name: bind
    facts:
      full_version: "{{ bind_version.full_version }}"
      version: "{{ bind_version.version }}"

...
