---

- name: configure pihole
  bodsch.dns.pihole_config:
    config: "{{ pihole_config | default({}) }}"
  when:
    - pihole_config | default({}) | count > 0
  notify:
    - restart pihole-FTL

- name: set pi-hole admin password
  bodsch.dns.pihole_admin_password:
    password: "{{ pihole_admin_password }}"
  when:
    - pihole_admin_password | default('') | string | length > 0

- name: create pihole groups
  bodsch.dns.pihole_groups:
    groups: "{{ pihole_groups | default([]) }}"
  when:
    - pihole_groups | default([]) | count > 0

- name: create pihole clients
  bodsch.dns.pihole_clients:
    clients: "{{ pihole_clients | default([]) }}"
  when:
    - pihole_clients | default([]) | count > 0

- name: create pihole adlists
  bodsch.dns.pihole_adlists:
    adlists: "{{ pihole_custom_denylists | default([]) }}"
  when:
    - pihole_custom_denylists | default([]) | count > 0
  notify:
    - pihole update gravity

- name: add custom lists
  bodsch.dns.pihole_custom_lists:
    allow_list: "{{ pihole_domain_allowlist | default([]) }}"
    deny_list: "{{ pihole_domain_denylist | default([]) }}"
  register: import_result
  changed_when: false
  notify:
    - pihole reload lists

