---

pdns_mysql_databases_credentials:
  'gmysql:one':
    'priv_user': root
    'priv_password': "{{ vault__pdns.database_root }}"
    'priv_host':
      - "localhost"

pdns_config:
  master: true
  slave: false
  also-notify: ""
  local-address: '127.0.0.1'
  local-port: '5300'
  log-dns-details: "on"
  loglevel: "3"

pdns_backends:
  'gmysql:one':
    'user': powerdns
    'host': localhost
    'password': "{{ vault__pdns.database_pdns }}"
    'dbname': pdns

# pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_44 }}"

# pdns_rec_config:
#   allow-from: "10.0.0.0/8"
#   local-address: "10.0.4.1"
#   forward-zones:
#     - matrix.lan=10.0.4.1:5300
#   webserver: true
#   webserver-address: "{{ ansible_default_ipv4.address }}"
#   webserver-port: 8082
#   webserver-allow-from:
#     - 127.0.0.1/32
#     - 10.0.2.4/32
#   webserver-loglevel: "normal"

...
