---

# pdns_mysql_databases_credentials:
#   'gmysql:one:
#     'priv_user: root
#     'priv_password: "{{ vault__pdns.databases.root }}"
#     'priv_host:
#       - "localhost"

pdns_config:
  master: true
  slave: false
  also-notify: ""
  local-address: '127.0.0.1'
  local-port: '5300'
  log-dns-details: "on"
  loglevel: "3"

# https://doc.powerdns.com/authoritative/backends/index.html?highlight=backend
pdns_backends:
  - name: 'gmysql:one'
    user: powerdns
    host: localhost
    password: "{{ vault__pdns.databases.pdns }}"
    dbname: pdns
    credentials: {}

  - name: 'gmysql:two'
    user: pdns_user
    host: 192.0.2.15
    port: 3307
    password: "{{ vault__pdns.databases.external }}"
    dbname: dns
    credentials: {}

  - name: bind
    config: '/etc/named/named.conf'
    hybrid:  true
    dnssec-db: '{{ pdns_config_dir }}/dnssec.db'

  - name: gsqlite3
    database: /var/lib/powerdns/pdns.db
    dnssec: true


# pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_44 }}"

# pdns_rec_config:
#   allow-from: "10.0.0.0/8"
#   local-address: "10.0.4.1"
#   forward-zones:
#     - matrix.lan=10.0.4.1:5300
#   webserver: true
#   webserver-address: "{{ ansible_default_ipv4.address }}"
#   webserver-port: 8082
#   webserver-allow-from:
#     - 127.0.0.1/32
#     - 10.0.2.4/32
#   webserver-loglevel: "normal"

...
